name: vwc_app
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.11.1

dependencies:
  flutter:
    sdk: flutter
  url_launcher: ^6.3.0
  cloudinary_public: ^0.23.1
  shared_preferences: ^2.2.3
  http: ^1.2.0
  crypto: ^3.0.3

  google_mlkit_document_scanner: ^0.2.0
  pdf: ^3.11.1
  printing: ^5.13.0
  share_plus: ^10.0.0
  cupertino_icons: ^1.0.8
  file_picker: ^8.0.0
  signature: ^5.5.0
  path_provider: ^2.1.6
  open_file: ^4.0.0
  qr_flutter: ^4.1.0
  local_auth: ^3.0.2
  flutter_secure_storage: ^9.0.0

  firebase_core: ^4.15.0
  cloud_firestore: ^6.10.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.1
  flutter_native_splash: ^2.4.1

flutter:
  uses-material-design: true
  assets:
    - assets/logos/vwc-logo.png

# Configuration to update App Launcher Icon on Android & iOS
flutter_launcher_icons:
  android: "ic_launcher"
  ios: true
  image_path: "assets/logos/vwc-logo.png"
  min_sdk_android: 21
  adaptive_icon_background: "#FFFFFF"
  adaptive_icon_foreground: "assets/logos/vwc-logo.png"

# Configuration to set Splash Screen Logo when App opens
flutter_native_splash:
  color: "#8B1E24"
  image: "assets/logos/vwc-logo.png"
  fullscreen: true
  android_12:
    image: "assets/logos/vwc-logo.png"
    icon_background_color: "#8B1E24"
    color: "#8B1E24"